### ISSUE TITLE
feature request: render markdown provided in context pane

### ISSUE THREAD

**Issue by curz46** [dhth/omm#11]
**Describe the solution you'd like**
The context pane's readability could benefit greatly from proper formatting. The context is already provided to the editor as a temporary ".md" file. Render markdown into the TUI whenever the context is displayed. 

It's probably out of scope for omm to provide a markdown renderer. However, perhaps an optional configurable property could accept a context renderer binary. The binary could be given as `/path/to/binary --arg1 --arg2 %p` where %p is replaced with the file path. The binary could be invoked, passed a temporary file as argument via `%p`, and the command output rendered in the context or task details pane.

This way an existing project like https://github.com/charmbracelet/glow can handle the actual markdown rendering.

**Is your feature request related to a problem? Please describe.**
I noticed the markdown written in the context editor is not rendered. 

**Describe alternatives you've considered**
Omm could provide a more opinionated solution, like pulling in `glow` as a library and optionally executing it.

**Comment by dhth** [comment]
Thanks for the input :)
`glamour` seems to be doing the job pretty well.
 
FYI, this is being worked on in #13.
