### ISSUE TITLE
 Arrow up/down don't work inside omm help

### ISSUE THREAD

**Issue by omnigenous** [dhth/omm#14]
**Describe the bug**

Arrow up/down don't work inside omm help

**Setup**

 - omm (devel) omm 0.4.0-1
 - zsh
 - kitty
 - en_US.UTF-8

**To Reproduce**
1. `omm`
2. `?`
3. `j` and `k` work but arrow up/down don't

**Expected behavior**

Arrow up/down should work as said in header:

>  help   (scroll with j/k/↓/↑)

**Comment by dhth** [comment]
My bad. It's added back in in `v0.4.2`.
