### ISSUE TITLE
Add confirmation before deleting a task

### ISSUE THREAD

**Issue by omnigenous** [dhth/omm#15]
**Describe the solution you'd like**

When pressing `ctrl+x` task gets deleted immediately without confirmation.
I think there should be a setting that enables confirmation dialog before deleting a task.

**Describe alternatives you've considered**

Be more careful with what I delete.

**Comment by dhth** [comment]
Good point. How about asking for `ctrl+x` twice?

**Comment by dhth** [comment]
Merged in [8be3a579](https://github.com/dhth/omm/commit/8be3a5794181cd9e1ff17b4c2490f1365abaa364).
