### ISSUE TITLE
[Feature request] Cycle tasks

### ISSUE THREAD

**Issue by danielwerg** [dhth/omm#19]
**Describe the solution you'd like**

Cycle tasks, when on first task and scrolling up move cursor to last item and when on last item and scrolling down move cursor to first item

**Is your feature request related to a problem? Please describe.**

When on last item and scrolling down or on first item and scrolling up nothing happens

**Describe alternatives you've considered**

Press `g` to go to top or `G` to go to bottom

**Comment by dhth** [comment]
This has been added in https://github.com/dhth/omm/commit/44aeaa246f68a11e5759c55a94ef881cf6396b46.

**Comment by dhth** [comment]
Hey @danielwerg. Quick note: I put circular navigation behind the flag `--circular-nav` and set it to OFF by default.
You can also enable it with `OMM_CIRCULAR_NAV=1 omm`, or by setting `circular_nav = true` in omm's TOML config file.
